spring:
  application:
    name: spring-bank
  datasource:
    url: jdbc:h2:mem:bank
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
